ManageHoteWeb/Controllers/BillsController.cs
using ManageHoteWeb.Data;
using ManageHoteWeb.Models;
using ManageHoteWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManageHoteWeb.Controllers
{
    public class BillsController : Controller
    {
        private readonly ManageHotelContext _context;

        public BillsController(ManageHotelContext context)
        {
            _context = context;
        }

        // GET: Bills
        public async Task<IActionResult> Index()
        {
            return View(await _context.Bill.ToListAsync());
        }

        // GET: Bills/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bill == null)
            {
                return NotFound();
            }

            var listRentalForm = _context.RentalForm.Include(r => r.Room.RoomType).Where(r => r.BillId == bill.Id).ToList();

            var viewModel = new DetailBillViewModel
            {
                Bill = bill,
                rentalRoomInBillView = new List<RentalRoomInBillView>()
            };

            if (listRentalForm.Count == 0)
                return View(viewModel);

            foreach (var rentalForm in bill.rentalForms)
            {
                var view = new RentalRoomInBillView();
                view.Room = rentalForm.Room.Name;
                view.NumberOfDayRent = rentalForm.NumberOfDayRental;
                view.Price = rentalForm.Room.RoomType.Price;

                rentalForm.Customers = _context.Customer.Include(c => c.CustomerType).Where(c => c.RentalFormId == rentalForm.id).ToList();
                view.SumPrice = rentalForm.SumPrice;

                viewModel.rentalRoomInBillView.Add(view);
            };

            return View(viewModel);
        }

        // GET: Bills/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(string customerName, string address ,IEnumerable<string> values)
        {
            Bill bill = new Bill
            {
                NameCustomer = customerName,
                Address = address,
                DayPayment = DateTime.Now,
            };

            _context.Add(bill);
            await _context.SaveChangesAsync();

            foreach(var item in values)
            {
                var rentalForm = _context.RentalForm
                    .Include(r=>r.Room.RoomType)
                    .Where(r => r.Room.Name == item)
                    .OrderByDescending(r=> r.DayRent)
                    .First();

                rentalForm.BillId = bill.Id;

                var listCustomerOfRentalForm = _context.Customer.Include(c => c.CustomerType).Where(c => c.RentalFormId == rentalForm.id).ToList();
                var numberOfDayRent = CalculateNumberOfDayRent(rentalForm.DayRent, bill.DayPayment);
                rentalForm.NumberOfDayRental = numberOfDayRent;
                rentalForm.SumPrice = CalculatePriceInRentalForm(numberOfDayRent, rentalForm.Room.RoomType.Price, listCustomerOfRentalForm);
                bill.SumPrice += rentalForm.SumPrice;

                _context.Update(rentalForm);
                await _context.SaveChangesAsync();
            }

            _context.Update(bill);
            await _context.SaveChangesAsync();

            return Json("Success");
        }

        // GET: Bills/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill.FindAsync(id);
            if (bill == null)
            {
                return NotFound();
            }
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameCustomer,SumPrice,DayPayment")] Bill bill)
        {
            if (id != bill.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillExists(bill.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bill);
        }

        // GET: Bills/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bill == null)
            {
                return NotFound();
            }

            var listRentalFormOfBill = _context.RentalForm.Where(r => r.BillId == bill.Id).ToList();
            
            if (listRentalFormOfBill.Count == 0)
                return View(bill);

            foreach (var rentalForm in listRentalFormOfBill)
            {
                rentalForm.BillId = null;
                _context.Update(rentalForm);
            }
            await _context.SaveChangesAsync();

            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bill = await _context.Bill.FindAsync(id);
            _context.Bill.Remove(bill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillExists(int id)
        {
            return _context.Bill.Any(e => e.Id == id);
        }

        public int CalculatePriceInRentalForm(int numberOfDay, int Price, List<Customer> customers)
        {
            var surchargeDb = _context.Surcharge.First();
                
            var surcharge  = customers.Count >= surchargeDb.NumberPeopleForSurcharge ? surchargeDb.Coefficent : 1;

            var coefficent = customers.Select(c => c.CustomerType.Coefficent).Max();

            return (int)(numberOfDay * Price * coefficent * surcharge);
        }

        public int CalculateNumberOfDayRent(DateTime start, DateTime end)
        {
            return (end - start ).TotalDays >= 1 ? (int)(end - start).TotalDays : 1;
        }
    }
}

ManageHoteWeb/Controllers/ListRoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManageHoteWeb.Data;
using ManageHoteWeb.Models;

namespace ManageHoteWeb.Controllers
{
    public class ListRoomsController : Controller
    {
        private readonly ManageHotelContext _context;

        public ListRoomsController(ManageHotelContext context)
        {
            _context = context;
        }

        // GET: ListRooms
        public async Task<IActionResult> Index(string room)
        {
            if (!String.IsNullOrEmpty(room))
            {
                return View(await _context.Room.Include(r => r.RoomType)
                    .Where(r => r.Name.Contains(room))
                    .OrderByDescending(r => r.Name).ToListAsync());
            }
            return View(await _context.Room.Include(r => r.RoomType)
                   .OrderByDescending(r => r.Name).ToListAsync());
        }

        private bool RoomExists(int id)
        {
            return _context.Room.Any(e => e.Id == id);
        }
    }
}

ManageHoteWeb/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManageHoteWeb.Data;
using ManageHoteWeb.Models;
using ManageHoteWeb.ViewModels;

namespace ManageHoteWeb.Controllers
{
    public class RoomsController : Controller
    {
        private readonly ManageHotelContext _context;

        public RoomsController(ManageHotelContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
            return View(await _context.Room.Include(r => r.RoomType).ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public  IActionResult Create()
        {
            RoomViewModel viewModel = new RoomViewModel
            {
                Room = new Room(),
                RoomTypes = _context.RoomType.ToList()
            };

            return View(viewModel);
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,RoomTypeId,Price,Status,MaxPerson,Note")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            RoomViewModel viewModel = new RoomViewModel
            {
                Room = room,
                RoomTypes = _context.RoomType.ToList()
            };
            return View(viewModel);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,RoomTypeId,Price,Status,MaxPerson,Note")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .Include(r =>r.RoomType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Room.FindAsync(id);
            _context.Room.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Room.Any(e => e.Id == id);
        }
    }
}

ManageHoteWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManageHoteWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Rooms" asp-action="Index">Danh mục phòng</a></li>
                    <li><a asp-area="" asp-controller="ListRooms" asp-action="Index">Danh sách phòng</a></li>
                    <li><a asp-area="" asp-controller="RentalForms" asp-action="Index">Phiếu thuê phòng</a></li>
                    <li><a asp-area="" asp-controller="Bills" asp-action="Index">Hóa đơn</a></li>
                    <li><a asp-area="" asp-controller="Surcharges" asp-action="Index">Quản lý quy định</a></li>
                    <li><a asp-area="" asp-controller="ListTypeRoomReports" asp-action="Index">Báo cáo theo loại phòng</a></li>
                    <li><a asp-area="" asp-controller="ListRoomReports" asp-action="Index">Báo cáo theo mật độ sử dụng</a></li> 

                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>



    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>