ManageHoteWeb/Models/Surcharge.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ManageHoteWeb.Models
{
    public class Surcharge
    {
        public int Id { get; set; }

        [Display(Name ="Số người tối thiểu cho phụ thu")]
        public int NumberPeopleForSurcharge { get; set; }

        [Display(Name = "Hệ số phụ thu")]
        public double Coefficent { get; set; }
    }
}

ManageHoteWeb/Controllers/RoomTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManageHoteWeb.Data;
using ManageHoteWeb.Models;

namespace ManageHoteWeb.Controllers
{
    public class RoomTypesController : Controller
    {
        private readonly ManageHotelContext _context;

        public RoomTypesController(ManageHotelContext context)
        {
            _context = context;
        }

        // GET: RoomTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.RoomType.ToListAsync());
        }

        // GET: RoomTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _context.RoomType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (roomType == null)
            {
                return NotFound();
            }

            return View(roomType);
        }

        // GET: RoomTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoomTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price")] RoomType roomType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(roomType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(roomType);
        }

        // GET: RoomTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _context.RoomType.FindAsync(id);
            if (roomType == null)
            {
                return NotFound();
            }
            return View(roomType);
        }

        // POST: RoomTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price")] RoomType roomType)
        {
            if (id != roomType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roomType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomTypeExists(roomType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roomType);
        }

        // GET: RoomTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _context.RoomType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (roomType == null)
            {
                return NotFound();
            }

            return View(roomType);
        }

        // POST: RoomTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roomType = await _context.RoomType.FindAsync(id);
            _context.RoomType.Remove(roomType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomTypeExists(int id)
        {
            return _context.RoomType.Any(e => e.Id == id);
        }
    }
}

ManageHoteWeb/Controllers/SurchargesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManageHoteWeb.Data;
using ManageHoteWeb.Models;

namespace ManageHoteWeb.Controllers
{
    public class SurchargesController : Controller
    {
        private readonly ManageHotelContext _context;

        public SurchargesController(ManageHotelContext context)
        {
            _context = context;
        }

        // GET: Surcharges
        public async Task<IActionResult> Index()
        {
            return View(await _context.Surcharge.ToListAsync());
        }


        // GET: Surcharges/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var surcharge = await _context.Surcharge.FindAsync(id);
            if (surcharge == null)
            {
                return NotFound();
            }
            return View(surcharge);
        }

        // POST: Surcharges/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NumberPeopleForSurcharge,Coefficent")] Surcharge surcharge)
        {
            if (id != surcharge.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(surcharge);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SurchargeExists(surcharge.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(surcharge);
        }

        private bool SurchargeExists(int id)
        {
            return _context.Surcharge.Any(e => e.Id == id);
        }
    }
}

ManageHoteWeb/Views/Surcharges/Edit.cshtml
@model ManageHoteWeb.Models.Surcharge

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Surcharge</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NumberPeopleForSurcharge" class="control-label"></label>
                <input asp-for="NumberPeopleForSurcharge" class="form-control" />
                <span asp-validation-for="NumberPeopleForSurcharge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Coefficent" class="control-label"></label>
                <input asp-for="Coefficent" class="form-control" />
                <span asp-validation-for="Coefficent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManageHoteWeb/Views/Surcharges/Index.cshtml
@model IEnumerable<ManageHoteWeb.Models.Surcharge>

@{
    ViewData["Title"] = "Quản lý";
}

<h2>Quản lý quy định</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumberPeopleForSurcharge)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Coefficent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberPeopleForSurcharge)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Coefficent)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<button class="btn btn-default">
    <a asp-area="" asp-controller="RoomTypes" asp-action="Index">Quản lý loại phòng</a>
</button>
<button class="btn btn-default">
    <a asp-area="" asp-controller="CustomerTypes" asp-action="Index">Quản lý loại khách</a>
</button>